"use client";
import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
type Guest = { id:string; name:string; max_party_size:number; revoked_at:string|null; invitation_responses:{attendance:string;party_size:number}|null };
type Data = { rows:Guest[];count:number;stats:{active:number;unanswered:number;people:number} };
export function AdminGuests({onExpired}:{onExpired:()=>void}) {
 const [name,setName]=useState("");const [quota,setQuota]=useState(1);const [busy,setBusy]=useState(false);const [status,setStatus]=useState("");
 const [search,setSearch]=useState("");const [query,setQuery]=useState("");const [page,setPage]=useState(0);const [data,setData]=useState<Data|null>(null);const [loading,setLoading]=useState(false);
 const [link,setLink]=useState<{name:string;url:string}|null>(null);const requestId=useRef("");const sequence=useRef(0);
 const load=useCallback(async()=>{const seq=++sequence.current;setLoading(true);try {const r=await fetch(`/api/admin/guests?${new URLSearchParams({q:query,page:String(page)})}`,{cache:"no-store"});const d=await r.json();if(seq!==sequence.current)return;if(r.status===401)onExpired();if(!r.ok)throw Error(d.error);setData(d);}catch(e){if(seq===sequence.current){setData(null);setStatus(e instanceof Error?e.message:"Gagal memuat tamu.");}}finally{if(seq===sequence.current)setLoading(false);}},[query,page,onExpired]);
 useEffect(()=>{void load();return()=>{sequence.current++;};},[load]);
 async function action(body:object){const r=await fetch("/api/admin/guests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(r.status===401)onExpired();if(!r.ok)throw Error(d.error);return d;}
 async function add(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setStatus("");requestId.current ||= crypto.randomUUID();try{await action({action:"create",id:requestId.current,name,quota});setName("");setQuota(1);requestId.current="";setStatus("Tamu berhasil ditambahkan. Gunakan Lihat / salin link untuk membagikan undangan.");await load();}catch(e){setStatus(e instanceof Error?e.message:"Belum dapat menyimpan. Coba lagi.");}finally{setBusy(false);}}
 async function showLink(g:Guest){setBusy(true);setStatus("");try{const d=await action({action:"link",id:g.id});setLink({name:g.name,url:d.url});}catch(e){setStatus(e instanceof Error?e.message:"Link belum dapat dimuat.");}finally{setBusy(false);}}
 async function revoke(g:Guest){if(!window.confirm(`Cabut akses undangan ${g.name}? Link tidak bisa dipakai lagi. Balasan tetap tersimpan.`))return;setBusy(true);setStatus("");try{await action({action:"revoke",id:g.id});setLink(null);setStatus("Akses undangan dicabut. Balasan tetap tersimpan.");await load();}catch(e){setStatus(e instanceof Error?e.message:"Gagal mencabut akses.");}finally{setBusy(false);}}
 return <div className="admin-guest-manager">
 <div className="admin-stats guest-stats">{([["active","Undangan aktif"],["unanswered","Belum menjawab"],["people","Orang akan hadir"]] as const).map(([key,label])=><article key={key}><strong>{data?data.stats[key]:"—"}</strong><p>{label}</p></article>)}</div>
 <p className="admin-help">Rekap ini menghitung tamu dengan tautan pribadi yang masih aktif. Jatah sudah termasuk penerima utama.</p>
 <section className="admin-inbox"><h2 className="admin-panel-title">Tambah tamu</h2><form className="admin-add-guest" onSubmit={add}><label>Nama penerima<input required maxLength={160} value={name} disabled={busy} onChange={e=>{setName(e.target.value);requestId.current="";}} /></label><label>Jatah orang<input type="number" min={1} max={20} required value={quota} disabled={busy} onChange={e=>{setQuota(Number(e.target.value));requestId.current="";}} /></label><button className="button" disabled={busy}>{busy?"Memproses…":"Tambah tamu"}</button></form><p className="admin-notice" role="status">{status}</p></section>
 {link&&<section className="admin-inbox admin-link-box"><h2 className="admin-panel-title">Undangan untuk {link.name}</h2><label>Tautan pribadi<input readOnly value={link.url} onFocus={e=>e.target.select()} /></label><div><button onClick={async()=>{try{await navigator.clipboard.writeText(link.url);setStatus("Tautan berhasil disalin.");}catch{setStatus("Pilih dan salin tautan secara manual dari kolom tautan pribadi.");}}}>Salin link</button><a className="button button-outline" href={link.url} target="_blank" rel="noreferrer">Buka undangan</a><button onClick={()=>setLink(null)}>Tutup</button></div><p className="admin-help">Tautan ini memberi akses RSVP penerima. Bagikan hanya kepada tamu yang bersangkutan.</p></section>}
 <section className="admin-inbox"><h2 className="admin-panel-title">Penerima undangan</h2><div className="admin-toolbar"><form onSubmit={e=>{e.preventDefault();setPage(0);setQuery(search);}}><label htmlFor="guest-search">Cari nama penerima</label><input id="guest-search" value={search} onChange={e=>setSearch(e.target.value)} /><button>Cari</button></form><button disabled={loading||busy} onClick={()=>void load()}>Muat ulang tamu</button></div>
 {loading?<p className="admin-empty">Memuat daftar tamu…</p>:!data?<p className="admin-empty">Daftar belum tersedia. Silakan muat ulang.</p>:<><p className="admin-help">{data.count} tamu ditemukan</p>{data.rows.length===0&&<p className="admin-empty">Belum ada tamu yang cocok. Tambahkan penerima melalui formulir di atas.</p>}{data.rows.map(g=><article className="admin-response admin-guest-row" key={g.id}><div><h3>{g.name}</h3><p>Jatah {g.max_party_size} orang · {g.revoked_at?"Akses dicabut":g.invitation_responses?g.invitation_responses.attendance==="hadir"?`Hadir ${g.invitation_responses.party_size} orang`:"Berhalangan":"Belum menjawab"}</p></div><div><button disabled={busy||!!g.revoked_at} onClick={()=>void showLink(g)}>Lihat / salin link</button><button disabled={busy||!!g.revoked_at} onClick={()=>void revoke(g)}>Cabut akses</button></div></article>)}<nav className="admin-pagination" aria-label="Halaman tamu"><span>Halaman {page+1}</span><div><button disabled={page===0} onClick={()=>setPage(page-1)}>Sebelumnya</button><button disabled={(page+1)*25>=data.count} onClick={()=>setPage(page+1)}>Berikutnya</button></div></nav></>}
 </section></div>;
}
