"use client";
import { useEffect, useRef, useState, type FormEvent } from "react";
export function invitationToken():string|null { const params=new URLSearchParams(window.location.search);return params.has("guest")?(params.getAll("guest").length===1?params.get("guest")!:""):null; }
type ResponseData={attendance:"hadir"|"berhalangan";party_size:number;message:string;publish_consent:boolean};
type Guest={name:string;max_party_size:number;invitation_responses:ResponseData|null};
async function api(body:object){const r=await fetch("/api/invitation",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body),signal:AbortSignal.timeout(15000)});const d=await r.json();if(!r.ok)throw Error(d.error);return d;}
export function GuestRecipient(){const [name,setName]=useState("");useEffect(()=>{const token=invitationToken();if(token!==null)void api({action:"resolve",token}).then(d=>setName(d.guest.name)).catch(()=>{});},[]);return name?<p className="cover-recipient">Kepada Yth.<br/><strong>{name}</strong></p>:null;}
export function PrivateResponse({token}:{token:string}) {
 const [guest,setGuest]=useState<Guest|null>(null);const [status,setStatus]=useState("");const [loading,setLoading]=useState(true);const [sending,setSending]=useState(false);const [saved,setSaved]=useState(false);
 const [attendance,setAttendance]=useState<"hadir"|"berhalangan">("hadir");const [party,setParty]=useState(1);const [message,setMessage]=useState("");const id=useRef("");const lock=useRef(false);const website=useRef<HTMLInputElement>(null);
 async function load(){setLoading(true);setStatus("");try{const d=await api({action:"resolve",token});setGuest(d.guest);const r=d.guest.invitation_responses;if(r){setAttendance(r.attendance);setParty(r.party_size||1);setMessage(r.message);setSaved(true);setStatus("Konfirmasi Anda sudah tersimpan. Anda dapat memperbaruinya bila diperlukan.");}}catch(e){setStatus(e instanceof Error?e.message:"Undangan belum dapat dimuat.");}finally{setLoading(false);}}
 useEffect(()=>{void load();},[token]);
 async function submit(e:FormEvent){e.preventDefault();if(lock.current||saved)return;lock.current=true;setSending(true);setStatus("");id.current ||= crypto.randomUUID();try{await api({action:"submit",token,requestId:id.current,attendance,partySize:attendance==="hadir"?party:0,message,publishConsent:true,website:website.current?.value||""});setSaved(true);setStatus("Terima kasih. Kehadiran dan doa Anda telah tersimpan."+(message?" Ucapan menunggu persetujuan keluarga.":""));}catch(e){setStatus(e instanceof Error?e.message:"Koneksi terputus. Coba kirim kembali.");}finally{lock.current=false;setSending(false);}}
 if(loading)return <p className="form-status">Memuat undangan pribadi…</p>;
 if(!guest)return <div><p role="status" className="form-status">{status}</p><button className="text-button" onClick={()=>void load()}>Coba lagi</button></div>;
 return <form onSubmit={submit} className="private-response"><fieldset className="response-fields" disabled={sending||saved}>
 <div className="form-field"><label className="small-label" htmlFor="private-name">Nama penerima</label><input id="private-name" readOnly value={guest.name}/><p className="admin-help">Undangan untuk maksimal {guest.max_party_size} orang, termasuk penerima utama.</p></div>
 <div className="form-field"><label className="small-label" htmlFor="private-attendance">Konfirmasi kehadiran</label><select id="private-attendance" value={attendance} onChange={e=>{setAttendance(e.target.value as "hadir"|"berhalangan");id.current="";}}><option value="hadir">Insya Allah Hadir</option><option value="berhalangan">Berhalangan</option></select></div>
 {attendance==="hadir"&&<div className="form-field"><label className="small-label" htmlFor="private-party">Jumlah yang hadir</label><select id="private-party" required value={party} onChange={e=>{setParty(Number(e.target.value));id.current="";}}>{Array.from({length:guest.max_party_size},(_,index)=><option key={index+1} value={index+1}>{index+1} orang</option>)}</select></div>}
 <div className="form-field"><label className="small-label" htmlFor="private-message">Untaian doa &amp; ucapan</label><textarea id="private-message" rows={3} maxLength={1000} value={message} onChange={e=>{setMessage(e.target.value);id.current="";}}/></div>
 <div className="form-trap" aria-hidden="true"><label>Website<input ref={website} tabIndex={-1} autoComplete="off"/></label></div>
 </fieldset><button className="button full-width" disabled={sending||saved}>{sending?"Mengirim…":saved?"Konfirmasi tersimpan":"Kirim ucapan & konfirmasi"}</button><p className="form-status" role="status">{status}</p>{saved&&<button type="button" className="text-button" onClick={()=>{setSaved(false);id.current="";setStatus("");}}>Ubah konfirmasi saya</button>}</form>;
}
